version: "3.7"

services:
  testexpo:
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=10.0.0.2
      - IMBA_DOCKER_TOKEN=$IMBA_DOCKER_TOKEN
    image: sonyarouje/expo-buster:latest
    extra_hosts:
      - "devserver:10.0.0.2"
    command: "--gitRepo github.com/morgandonze/Imba --pat ${IMBA_DOCKER_TOKEN}"
    # command: sh -c "yarn install && yarn run dev"
    expose:
      - "19000"
      - "19001"
      - "19002"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - myexpo:/home/node/src
volumes:
  myexpo:
